INSERT INTO LANGUAGE VALUES(1,'JavaScript')

INSERT INTO CONFIGURATION VALUES(1,'Rest API with nodejs and the express tool','nodejs-express','nodejs-express')

INSERT INTO OPERATINGSYSTEM VALUES(1,'Windows','windows')

INSERT INTO LANGUAGE_CONFIGURATION VALUES(1,1)

INSERT INTO CONFIGURATION_OPERATINGSYSTEM VALUES(1,1)

INSERT INTO OPERATINGSYSTEM VALUES(2,'Ubuntu','linux')

INSERT INTO CONFIGURATION_OPERATINGSYSTEM VALUES(1,2)

INSERT INTO OPERATINGSYSTEM VALUES(3,'Debian','linux')

INSERT INTO CONFIGURATION_OPERATINGSYSTEM VALUES(1,3)
